### ISSUE TITLE
Errors when running Geometry optimizations

### ISSUE THREAD

**Issue by alejandrosantanabonilla** [pyscf/semiempirical#4]
Hi there! I have been trying to perform geometry optimizations with the semiempirical approach and I have discovered that there is a misspelling in the following lines:

Class RMINDO3   line 175  from pyscf import semiemprical   -> from pyscf import semiempirical 
Class UMINDO3   line 253  from pyscf import semiemprical   -> from pyscf import semiempirical 

Once these two misspellings are corrected the geometry optimization is performed. I hope this error is corrected in the repo since 
for the moment I need to clone the code, correct it myself in order to be able to use it. Thanks in advance.

**Comment by gkc1000** [comment]
Thanks for noticing this: can you please submit a pull request? Then you
are part of the developer community!

**Comment by sunqm** [comment]
Fixed in PR #5
