### ISSUE TITLE
PyPI release does not contains C extensions files

### ISSUE THREAD

**Issue by ccoulombe** [pyscf/semiempirical#8]
The sdist on PyPI is missing some files versus the github repository : https://pypi.org/project/pyscf-semiempirical/#files
Namely, the c extensions files:
```
$ tar --list -f pyscf-semiempirical-0.1.0.tar.gz | fgrep -e '*.c'
$ 
```
This results in a universal wheel without the library.

Can the PyPi release be yanked in favor of one that contains the c files?

**Comment by sunqm** [comment]
The new release https://pypi.org/project/pyscf-semiempirical/#files has included the necessary C files
